version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user_password
      POSTGRES_DB: dockerdb
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
  app:
    build: ./application
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/dockerdb
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: user_password
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
      SPRING_JPA_HIBERNATE_DDL-AUTO: update
      SERVER_PORT: 8000
      JWT_DEV: false
  subapp:
    build: ./subapplication
    ports:
      - "8080:8080"

volumes:
  data: